name: GitHub Actions Demo
run-name: oblig2software/src/test/java/testisleapyear.java
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ oblig2software/src/test/java/testisleapyear.java  }}
